#!/bin/bash

set -eu

if [ "${1:-}" = "--semantic-apps" ]; then
    echo downloading semantic-apps...
    echo $GH_API_TOKEN | gh auth login --with-token
    gh release download --repo gesinn-it/semantic-apps-factory --pattern mediawiki-backup.tar --dir /tmp
    BACKUP_FILE=/tmp/mediawiki-backup.tar
else
    BACKUP_FILE=/backup/mediawiki-backup.tar
fi

TMP_FOLDER=`mktemp -d`
cd $TMP_FOLDER

tar xf $BACKUP_FILE

# show version
echo backup by mediawiki-backup version `cat mediawiki-backup.version`

# restoring db
echo restoring mysql db
bzip2 -d mysqldump.sql.bz2
MYSQL_PWD=$MYSQL_ROOT_PASSWORD mysql --default-character-set=utf8 wiki < mysqldump.sql

# restoring images
echo restoring images
rm -rf /var/www/html/images/* /var/www/html/images/.??*
tar -xf $BACKUP_FILE -C /var/www/html

echo restored $BACKUP_FILE
