#!/bin/bash

set -eu

if [ "${1:-}" = "gh-asset" ]; then
    echo downloading github release asset...
    REPO=${2:-}
    PATTERN=${3:-}
    VERSION=${4:-}
    if [ "$REPO" = "" -o "$PATTERN" = "" ]; then
        echo "usage: restore gh-asset <REPOSITORY> <ASSET-NAME> [<VERSION>]"
        exit 1
    fi
    echo $GH_API_TOKEN | gh auth login --with-token
    gh release download $VERSION --repo $REPO --pattern $PATTERN --dir /tmp
    BACKUP_FILE=/tmp/$PATTERN
else
    BACKUP_FILE=/backup/mediawiki-backup.tar
fi

TMP_FOLDER=`mktemp -d`
cd $TMP_FOLDER

# show version
tar xf $BACKUP_FILE mediawiki-backup.version
echo backup This backup has been made by mediawiki-backup version `cat mediawiki-backup.version`

# restoring db
echo restoring mysql db
tar xf $BACKUP_FILE mysqldump.sql.bz2
bzip2 -d mysqldump.sql.bz2
MYSQL_PWD=$MYSQL_ROOT_PASSWORD mysql --default-character-set=utf8 wiki < mysqldump.sql
MYSQL_PWD=$MYSQL_ROOT_PASSWORD mysqlcheck -h $MYSQL_HOST --repair --database wiki

# restoring images
echo restoring images
rm -rf /var/www/html/images/* /var/www/html/images/.??*
tar -C /var/www/html -xf $BACKUP_FILE images

echo restored $BACKUP_FILE
